controller_list:
  - name: fake_L_xarm7_controller
    type: $(arg fake_execution_type)
    joints:
      - L_joint1
      - L_joint2
      - L_joint3
      - L_joint4
      - L_joint5
      - L_joint6
      - L_joint7
  - name: fake_R_xarm7_controller
    type: $(arg fake_execution_type)
    joints:
      - R_joint1
      - R_joint2
      - R_joint3
      - R_joint4
      - R_joint5
      - R_joint6
      - R_joint7
  - name: fake_L_xarm_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - L_drive_joint
  - name: fake_R_xarm_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - R_drive_joint
initial:  # Define initial robot poses per group
  - group: L_xarm7
    pose: left_home
  - group: R_xarm7
    pose: right_home
  - group: L_xarm_gripper
    pose: L_open
  - group: R_xarm_gripper
    pose: R_open